version: '3.8'

services:
  res-menu-db:
    image: postgres
    container_name: res-menu-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: menu_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/pgdata_employee:/var/lib/postgresql/data

  res-menu-api:
    container_name: res-menu-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
